name: musicplayer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  on_audio_query: ^2.6.1
  just_audio_background: ^0.0.1-beta.7
  provider: ^6.0.3
  just_audio: ^0.9.29
  sleek_circular_slider: ^2.0.1
  cupertino_icons: ^1.0.2
  palette_generator: ^0.3.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

